model: yolo11n.pt
data: dataset/yolo_cholecTrack20/cholecTrack20.yaml
project: results/logs
name: yolov11_cholectrack20
weights_dir: results/weights

epochs: 100
batch: 16
imgsz: 640
lr0: 0.01
lrf: 0.01
optimizer: SGD
weight_decay: 0.0005
warmup_epochs: 3
device: "0"
